// content.js
const textWW = `
Primul Război Mondial (28 iulie 1914 – 11 noiembrie 1918) a fost unul dintre cele mai mortale conflicte globale din istorie. El a opus două coaliții, prima fiind Antanta, având ca nucleu Franța, Regatul Unit, Rusia, Italia, Japonia și imperiile lor coloniale respective, cu Statele Unite aderând ca putere asociată în 1917. Aceasta s-a confruntat cu Puterile Centrale, o alianță centrată pe Germania, Austro-Ungaria și Imperiul Otoman. Luptele au avut loc în toată Europa, Orientul Mijlociu, Africa, Pacific și în părți din Asia. Aproximativ 9 milioane de soldați au fost uciși în luptă, plus alte 23 de milioane de răniți, în timp ce 5 milioane de civili au murit ca urmare a acțiunii militare, a foametei și a bolilor.[5] Alte milioane au murit ca urmare a genocidelor, în timp ce pandemia de gripă spaniolă din 1918 a fost exacerbată de mișcarea combatanților în timpul războiului.[6][7]

Primul deceniu al secolului al XX-lea a fost o perioadă de tensiuni diplomatice crescânde între marile puteri europene. Acestea au atins un punct de rupere pe 28 iunie 1914, când un sârb bosniac⁠(d) pe nume Gavrilo Princip l-a asasinat pe arhiducele Franz Ferdinand, moștenitorul tronului Austro-Ungariei. Austro-Ungaria a considerat Serbia responsabilă și, în ciuda eforturilor diplomatice de a rezolva conflictul, a declarat război pe 28 iulie. Rusia a venit în apărarea Serbiei, iar până la 4 august, alianțe defensive suprapuse au atras în conflict Franța, Regatul Unit și Germania.

Strategia germană în 1914 a fost să învingă mai întâi Franța, apoi să își mute trupele spre est și să facă același lucru cu Rusia.[8] Acest plan a eșuat și, până la sfârșitul anului 1914, Frontul de Vest consta dintr-o linie continuă de tranșee care se întindea de la Canalul Mânecii până în Elveția. Frontul de Est era mai fluid, dar niciuna dintre părți nu a putut obține un avantaj decisiv, în ciuda unei serii de ofensive costisitoare. Încercările de a ocoli impasul au făcut ca luptele să se extindă în Orientul Mijlociu, Alpi, Balcani și coloniile de peste mări, aducând Bulgaria, România, Grecia⁠(d) și altele în război.

Statele Unite au intrat în război⁠(d) de partea Antantei în aprilie 1917, în timp ce bolșevicii preluau puterea în Revoluția din octombrie din Rusia și au făcut pace separată cu Puterile Centrale la începutul anului 1918. Degrevată de Frontul de Est, Germania a lansat o ofensivă⁠(d) în vest în martie 1918, sperând să obțină o victorie decisivă acolo înainte ca trupele americane să sosească în număr semnificativ. Eșecul a lăsat armata imperială germană epuizată și demoralizată. Când aliații au preluat inițiativa și au lansat propria lor ofensivă în august 1918, germanii nu au putut face altceva decât să o încetinească.[9]

Între 29 septembrie și 3 noiembrie 1918, Bulgaria, Imperiul Otoman și Austro-Ungaria au acceptat armistiții cu Aliații, lăsând Germania izolată. Confruntată cu revoluția în interior și cu armata în pragul revoltei, Kaiserul Wilhelm al II-lea a abdicat pe 9 noiembrie. Armistițiul din 11 noiembrie 1918 a pus capăt luptelor, iar Conferința de Pace de la Paris a impus diverse reglementări puterilor înfrânte, cel mai cunoscut fiind Tratatul de la Versailles. Dizolvarea Imperiilor Rus, German, Austro-Ungar și Otoman a dus la crearea de noi state independente, printre care Polonia, Cehoslovacia și Iugoslavia. Din motive aflate încă în discuție, eșecul de a gestiona instabilitatea care a rezultat din această perturbare în perioada interbelică a contribuit la declanșarea celui de al Doilea Război Mondial în septembrie 1939.

Denumiri
Termenul de război mondial a fost avansat pentru prima dată în septembrie 1914 de către biologul și filozoful german Ernst Haeckel. El afirma că „nu există nicio îndoială că desfășurarea și caracterul temutului «război european» ... va deveni primul război mondial în sensul deplin al cuvântului”,[10] în The Indianapolis Star⁠(d) pe 20 septembrie 1914.

Termenul Primul Război Mondial fusese folosit de lt-col. Charles à Court Repington⁠(d), ca titlu pentru memoriile sale (publicate în 1920); el a consemnat discuția pe care o purtase cu un anume maior Johnstone la Universitatea Harvard în jurnalul său din 10 septembrie 1918.[11] Înainte de al Doilea Război Mondial, evenimentele din 1914–1918 erau cunoscute în general ca Marele Război sau pur și simplu Războiul Mondial.[12][13] În august 1914, revista The Independent⁠(d) a scris „Acesta este Marele Război. Numele vine de la sine”. În octombrie 1914, revista canadiană Maclean's⁠(d) a scris în mod similar: „Unele războaie au o denumire care vine natural. Acesta este Marele Război.”[14] Europenii contemporani l-au denumit „războiul care va pune capăt oricărui război” și a fost descris și drept „războiul care va pune capăt tuturor războaielor”, datorită percepției pe care o aveau ei asupra amplorii, devastării și pierderii de vieți omenești fără egal până atunci.[15]


Primul Război Mondial (28 iulie 1914 – 11 noiembrie 1918) a fost unul dintre cele mai mortale conflicte globale din istorie. El a opus două coaliții, prima fiind Antanta, având ca nucleu Franța, Regatul Unit, Rusia, Italia, Japonia și imperiile lor coloniale respective, cu Statele Unite aderând ca putere asociată în 1917. Aceasta s-a confruntat cu Puterile Centrale, o alianță centrată pe Germania, Austro-Ungaria și Imperiul Otoman. Luptele au avut loc în toată Europa, Orientul Mijlociu, Africa, Pacific și în părți din Asia. Aproximativ 9 milioane de soldați au fost uciși în luptă, plus alte 23 de milioane de răniți, în timp ce 5 milioane de civili au murit ca urmare a acțiunii militare, a foametei și a bolilor.[5] Alte milioane au murit ca urmare a genocidelor, în timp ce pandemia de gripă spaniolă din 1918 a fost exacerbată de mișcarea combatanților în timpul războiului.[6][7]

Primul deceniu al secolului al XX-lea a fost o perioadă de tensiuni diplomatice crescânde între marile puteri europene. Acestea au atins un punct de rupere pe 28 iunie 1914, când un sârb bosniac⁠(d) pe nume Gavrilo Princip l-a asasinat pe arhiducele Franz Ferdinand, moștenitorul tronului Austro-Ungariei. Austro-Ungaria a considerat Serbia responsabilă și, în ciuda eforturilor diplomatice de a rezolva conflictul, a declarat război pe 28 iulie. Rusia a venit în apărarea Serbiei, iar până la 4 august, alianțe defensive suprapuse au atras în conflict Franța, Regatul Unit și Germania.

Strategia germană în 1914 a fost să învingă mai întâi Franța, apoi să își mute trupele spre est și să facă același lucru cu Rusia.[8] Acest plan a eșuat și, până la sfârșitul anului 1914, Frontul de Vest consta dintr-o linie continuă de tranșee care se întindea de la Canalul Mânecii până în Elveția. Frontul de Est era mai fluid, dar niciuna dintre părți nu a putut obține un avantaj decisiv, în ciuda unei serii de ofensive costisitoare. Încercările de a ocoli impasul au făcut ca luptele să se extindă în Orientul Mijlociu, Alpi, Balcani și coloniile de peste mări, aducând Bulgaria, România, Grecia⁠(d) și altele în război.

Statele Unite au intrat în război⁠(d) de partea Antantei în aprilie 1917, în timp ce bolșevicii preluau puterea în Revoluția din octombrie din Rusia și au făcut pace separată cu Puterile Centrale la începutul anului 1918. Degrevată de Frontul de Est, Germania a lansat o ofensivă⁠(d) în vest în martie 1918, sperând să obțină o victorie decisivă acolo înainte ca trupele americane să sosească în număr semnificativ. Eșecul a lăsat armata imperială germană epuizată și demoralizată. Când aliații au preluat inițiativa și au lansat propria lor ofensivă în august 1918, germanii nu au putut face altceva decât să o încetinească.[9]

Între 29 septembrie și 3 noiembrie 1918, Bulgaria, Imperiul Otoman și Austro-Ungaria au acceptat armistiții cu Aliații, lăsând Germania izolată. Confruntată cu revoluția în interior și cu armata în pragul revoltei, Kaiserul Wilhelm al II-lea a abdicat pe 9 noiembrie. Armistițiul din 11 noiembrie 1918 a pus capăt luptelor, iar Conferința de Pace de la Paris a impus diverse reglementări puterilor înfrânte, cel mai cunoscut fiind Tratatul de la Versailles. Dizolvarea Imperiilor Rus, German, Austro-Ungar și Otoman a dus la crearea de noi state independente, printre care Polonia, Cehoslovacia și Iugoslavia. Din motive aflate încă în discuție, eșecul de a gestiona instabilitatea care a rezultat din această perturbare în perioada interbelică a contribuit la declanșarea celui de al Doilea Război Mondial în septembrie 1939.

Denumiri
Termenul de război mondial a fost avansat pentru prima dată în septembrie 1914 de către biologul și filozoful german Ernst Haeckel. El afirma că „nu există nicio îndoială că desfășurarea și caracterul temutului «război european» ... va deveni primul război mondial în sensul deplin al cuvântului”,[10] în The Indianapolis Star⁠(d) pe 20 septembrie 1914.


`


export default textWW;
